//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaLogWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("LuaLog");
		L.RegFunction("OpenLibs", OpenLibs);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenLibs(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaInterface.LuaState arg0 = (LuaInterface.LuaState)ToLua.CheckObject<LuaInterface.LuaState>(L, 1);
			LuaLog.OpenLibs(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

